name:                homodoro
version:             0.1.0.0
github:              "c0nradLC/homodoro"
license:             BSD3
author:              "Leonardo Palhano Conrado"
maintainer:          "l.conrado10@gmail.com"
copyright:           "2024 Leonardo Conrado"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple#readme>

dependencies:
  - base >= 4.7 && < 5
  - brick
  - vty
  - lens
  - mtl
  - text
  - gi-notify
  - directory
  - filepath
  - vector
  - ALUT
  - file-embed
  - bytestring
  - temporary
  - aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
  - src

executables:
  homodoro:
    main:                Main.hs
    source-dirs:         
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homodoro

tests:
  homodoro-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homodoro
